[versions]
agp = "8.12.3"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
impress = "0.0.7"
firebaseCrashlyticsBuildtools = "3.0.6"
firebaseDatabase = "22.0.1"
rendering = "1.17.1"
firebaseStorage = "22.0.1"
datastoreCore = "1.2.0"
contentpager = "1.0.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
impress = { group = "com.google.ar", name = "impress", version.ref = "impress" }
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
rendering = { group = "com.google.ar.sceneform", name = "rendering", version.ref = "rendering" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage", version.ref = "firebaseStorage" }
datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastoreCore" }
contentpager = { group = "androidx.contentpager", name = "contentpager", version.ref = "contentpager" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

